REM ================= PSX DEVELOPMENT ENVIRONMENT VARIABLES =============
REM       RELEASE 1.8 LIBRARY 3.6.1 Date: 1-31-1998 Time: 21:38:44
set PATH=D:\psyq\bin;
set PSX_PATH=D:\psyq\bin
set LIBRARY_PATH=D:\psyq\lib
set C_PLUS_INCLUDE_PATH=D:\psyq\include
set C_INCLUDE_PATH=D:\psyq\include
set PSYQ_PATH=D:\psyq\bin

set COMPILER_PATH=D:\psyq\bin
set GO32=DPMISTACK 1000000 
set G032TMP=D:\TEMP
set TMPDIR=D:\TEMP

CPE2X.EXE BUILD.CPE >> d:\LOG.TXT

EXIT
